Ben/memberapp
SCE-Development/Core-v4 pull request #1092
Opened 2022-05-30 23:49 UTC by KuroyukiRyuu

Works for mobile, but doesn't work for desktop when resizing at certain resolutions. I think it should be fine if the background color is black?

2022-06-02 03:24 UTC, neelp03 requested changes
🔥 This looks so good. Don't forget to resolve merge conflicts. I do have a few suggestions. I think the membership plans visual could be a bit smaller for mobile view but its up to you.

There is also a lot of commented out code (mostly in the css files) which should be removed.
You should also stick to the naming conventions we have been using. JS files would follow pascal case which is like this: "PascalCase" and CSS files are camel case which is like this: "camelCase".

2022-06-02 03:26 UTC, neelp03 commented
One more thing, don't commit/push package.json and package-lock.json unless you are using new dependencies.

2022-06-03 05:57 UTC, neelp03 requested changes
Membership app tests lgtm! I think you missed one file while renaming to follow the appropriate naming convention ([src/Pages/MembershipApplication/membershipApplication.jsx](https://github.com/SCE-Development/Core-v4/blob/022c46343959e76063d3f71db33b011e685e1904/src/Pages/MembershipApplication/membershipApplication.jsx)). It should follow pascal case which is basically camel case but it starts with uppercase.

2022-06-03 06:14 UTC, evanugarte commented on src/Pages/MembershipApplication/registerPage.css
> +body {
in react, adding a rule for `body` in one css file will apply it to the whole project, same as the rules below for h1, h2, etc.

to fix this lets not use generic selectors and instead use class names, a good example of this is [src/Pages/3DPrinting/3D-print-form.css:27](https://github.com/SCE-Development/Core-v4/blob/053a0dae3380f93319107e9ebd43e61d1fab07b2/src/Pages/3DPrinting/3D-print-form.css#L27)

2022-06-04 02:45 UTC, neelp03 requested changes
Every once in a while api-tests in github actions or checks will fail. If it seems like an odd error like something that is completely unrelated to your changes then just re-run all jobs via checks tab which should fix it. The frontend tests failed because you still have a path to a deleted file in your member app tests so removing that line should fix it.

2022-06-04 02:47 UTC, neelp03 approved these changes

2022-06-04 16:25 UTC, evanugarte commented
This looks good, 2 things
1. the name inputs arent aligned like the others
2. white area at the bottom depending on window size

i can show u how to fix these
![image](https://user-images.githubusercontent.com/36345325/172016048-311b7a85-5ca8-4f85-a549-7353918858d9.png)

2022-07-28 07:16 UTC, evanugarte approved these changes
summer walker once said
![image](https://user-images.githubusercontent.com/36345325/181444493-0a654859-bafb-420a-beae-ec275b5eae6c.png)

2022-07-28 13:16 UTC, neelp03 approved these changes

2022-07-28 13:16 UTC, merged