Add Membership Expiration Date
SCE-Development/Core-v4 pull request #1105
Opened 2022-06-25 20:04 UTC by davidtanline

Shows membership expiration date in dropdown menu when editing user's membership expiration as admin.

<img width="1440" alt="updatedMembershipExpDate" src="https://user-images.githubusercontent.com/57863253/175788957-d2df752d-7b05-4ff8-9467-1c500642876b.png">

2022-06-25 22:36 UTC, ShaivPandya approved these changes

2022-06-29 02:35 UTC, ShaivPandya approved these changes

2022-07-04 23:08 UTC, davidtanline commented
<img width="1440" alt="Screen Shot 2022-07-04 at 3 59 50 PM" src="https://user-images.githubusercontent.com/57863253/177224094-33c0ffee-d8ac-4c72-8c2f-a5e866c6f021.png">
<img width="1356" alt="Screen Shot 2022-07-04 at 4 06 18 PM" src="https://user-images.githubusercontent.com/57863253/177224099-8f9c6d8b-5533-401a-a637-0389776bb7a5.png">

New AdminDashboard landing page UI and modified navbar links

2022-07-05 06:01 UTC, neelp03 approved these changes

2022-07-07 21:38 UTC, neelp03 requested changes
You have some merge conflicts. Also, for the functions you wrote can you add documentation in JS syntax please. Use these for reference: 
- [Inline JS Documentation Guide](https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript/)
- [Documentation example in Core-v4](https://github.com/SCE-Development/Core-v4/blob/dev/api/peripheral_api/util/RFID-helpers.js#L10:L15)

2022-07-07 23:09 UTC, neelp03 commented
Also put writeToSQS in a new folder called tools

2022-07-08 23:00 UTC, evanugarte approved these changes

2022-07-08 23:16 UTC, neelp03 requested changes

2022-07-08 23:16 UTC, neelp03 commented on api/main_endpoints/util/registerUser.js
> +/**
add documentation for this too using the js documentation guide
you can also document parameters using @params ... 
all in the guide

2022-07-09 01:57 UTC, neelp03 approved these changes

2022-07-09 01:57 UTC, merged