Profile
SCE-Development/Core-v4 pull request #1110
Opened 2022-07-04 20:46 UTC by ekanshgupta123

change profile component

2022-07-07 01:30 UTC, neelp03 requested changes
Checked it locally and everything works. Just a few minor suggestions below.

2022-07-07 01:30 UTC, neelp03 commented on src/Pages/Profile/admin/editor-form.css
> +    line-height: 10px;
syntax got messed up here

2022-07-07 01:30 UTC, neelp03 commented on test/frontend/Profile.test.js
Where are the tests for this component?

2022-07-07 01:30 UTC, neelp03 commented on src/Pages/Profile/admin/Profile.js
> +      <h3 style = {{fontWeight: 'bold', textAlign: 'center'}}>
do styling in css file to keep it clean

2022-07-09 01:31 UTC, neelp03 approved these changes

2022-07-09 01:36 UTC, akshtshrma24 commented on src/Pages/Profile/admin/editor-form.css
> +h3 {
scope these otherwise it will do global h3 css

2022-07-09 02:57 UTC, neelp03 approved these changes

2022-07-09 03:02 UTC, evanugarte approved these changes

2022-07-09 03:03 UTC, merged