Add currentUsers function
SCE-Development/Core-v4 pull request #1143
Opened 2022-08-24 22:42 UTC by davidtanline

2022-08-24 22:48 UTC, evanugarte commented on test/api/User.js
> +  describe('/GET currentUsers', () => {
can u add a test case for making sure it returns JSON data of users?

2022-08-25 17:27 UTC, neelp03 requested changes
Merge conflicts...a lot of them
also there were a few random spaces in User.js file in routes

2022-08-26 05:57 UTC, evanugarte approved these changes

2022-08-27 02:28 UTC, neelp03 approved these changes

2022-08-27 06:38 UTC, ShaivPandya approved these changes

2022-08-29 19:27 UTC, merged