add PageNumbers component for User Pagination
SCE-Development/Core-v4 pull request #1149
Opened 2022-08-29 19:41 UTC by davidtanline

2022-08-30 17:45 UTC, neelp03 reviewed
Can you add a description to what this does please?

2022-09-06 15:58 UTC, neelp03 approved these changes

2022-09-06 16:15 UTC, ShaivPandya requested changes

2022-09-06 16:15 UTC, ShaivPandya commented on src/Pages/Overview/PageNumbers.js
> +  // const currentPage = params.page ? parseInt(params.page) : 1;
Delete commented variable of the same name

2022-09-15 18:59 UTC, ShaivPandya approved these changes

2022-09-16 06:41 UTC, merged