Fixed Minimization Error with Dark Mode
SCE-Development/Core-v4 pull request #620
Opened 2020-09-02 02:49 UTC by fmasood23

Resolves #619

2020-09-02 07:41 UTC, fmasood23 commented
> the navbar's css got messed up
> <img alt="Screen Shot 2020-09-02 at 12 02 56 AM" width="838" src="https://user-images.githubusercontent.com/50391828/91942422-c793b700-ecaf-11ea-8afd-bd758cdaf68e.png">

fixed this! this shouldn't happen anymore

2020-09-02 15:16 UTC, fmasood23 commented
> <img alt="Screen Shot 2020-09-02 at 1 17 06 AM" width="189" src="https://user-images.githubusercontent.com/50391828/91958006-a1741400-ecbb-11ea-8ef0-9df75edc4b47.png">
> 
> The toggler is vertically aligned, could you vertically center it?

Let me know how it looks now!

2020-09-04 20:08 UTC, jerrylee17 approved these changes

2020-09-04 20:24 UTC, IsitaB requested changes
it works, but get rid of inline styling

2020-09-04 20:24 UTC, IsitaB commented on src/Components/Navbar/UserNavbar.js
> +        <div align='left' style={{
move styling to css file

2020-09-04 20:31 UTC, aashrav approved these changes
Looks good

2020-09-05 06:22 UTC, IsitaB approved these changes

2020-09-05 07:22 UTC, qsaml commented
seems to work for me as well

2020-09-05 23:41 UTC, IsitaB approved these changes

2020-09-06 01:11 UTC, merged