resumeGeneratorFormv3
SCE-Development/Core-v4 pull request #625
Opened 2020-09-05 22:58 UTC by Gremlinbaby

hello, please look at this 👍 
You can put in the information or just spam next page and click submit 👍 
That is all 👍

2020-09-05 23:27 UTC, IsitaB reviewed
fix adminnavbar frontend tests

2020-09-05 23:32 UTC, qsaml commented
is it just me, or does no pdf download?

some fields could be more intuitive. ones that say "type skills here" should have an additional specifier, maybe "separated by commas"

page itself looks really clean though

2020-09-09 03:38 UTC, IsitaB requested changes
it works!! 🔥🔥🔥
<img width="577" alt="Screen Shot 2020-09-08 at 8 15 52 PM" src="https://user-images.githubusercontent.com/50391828/92551506-06c38a00-f213-11ea-8033-e60052cdb3bc.png">
fix this. you use "class" but you should be using "className" instead

you need padding bottom for your page

rebase

2020-09-09 03:38 UTC, IsitaB commented on src/Components/Navbar/UserNavbar.js
> +                  </DropdownToggle>
I guess the insides didnt get indented. just `OPT+SHIFT+F` this file

2020-09-09 03:38 UTC, IsitaB commented on src/Pages/Resume/Education.js
> +    const nameStyle = {
move it to your css file

2020-09-09 03:38 UTC, IsitaB commented on src/Pages/Resume/Experience.js
> +    const nameStyle = {
this is the same as the other nameStyle. move it to a css file. DRY

2020-09-09 03:38 UTC, IsitaB commented on src/Pages/Resume/GeneralInformation.js
> +    return(
I'd say use arrays and map functions. these form groups all look similar

2020-11-13 03:41 UTC, closed without merging

2020-11-13 03:42 UTC, jerrylee17 commented
See #661