Added Manager For DoorCode
SCE-Development/Core-v4 pull request #698
Opened 2020-11-15 02:29 UTC by SlicerBX

2020-12-20 02:09 UTC, SlicerBX commented
Integrated previous implemented backend with newly added front end for managing door codes from admin.

Testing:

1. Login into your admin account. Once logged in, go to the admin dashboard located under the account name on the right of navbar. Once there, click on Door Codes on the nav bar, you should see the following:
<img width="1514" alt="Screen Shot 2020-12-19 at 5 49 33 PM" src="https://user-images.githubusercontent.com/54377995/102703523-ba7de200-4224-11eb-949a-48de8e70d865.png">

2. To add a door code, click on the + button and fill out the text fields (Door Code and Expire Date). Note that a door code can only be a sequence of seven numbers with a dash after the third number (i.e. ###-####). Note that you can add more than one door code by creating a new line in the text box. Click on the Add Door Codes button to add them to the table manager.
<img width="496" alt="Screen Shot 2020-12-19 at 6 00 49 PM" src="https://user-images.githubusercontent.com/54377995/102703566-3d9f3800-4225-11eb-9e05-afd20c144dda.png">

<img width="1046" alt="Screen Shot 2020-12-19 at 6 01 56 PM" src="https://user-images.githubusercontent.com/54377995/102703540-e5683600-4224-11eb-9d6c-581be17dca7f.png">

3. To edit a single door code, click on the edit icon associated with the door code and input your new door code sequence and expire date. Click on the edit button once all fields are inputted.
<img width="493" alt="Screen Shot 2020-12-19 at 6 02 26 PM" src="https://user-images.githubusercontent.com/54377995/102703547-03359b00-4225-11eb-81b4-23740dd59bc5.png">

4. To delete a door code, click on the trash icon associated with the door code. A warning message will pop up. To verify the deletion, click yes and the table will update with the deleted door code removed.
<img width="494" alt="Screen Shot 2020-12-19 at 6 02 44 PM" src="https://user-images.githubusercontent.com/54377995/102703554-0f215d00-4225-11eb-97b9-c02c89b0952c.png">

5. To delete all door codes that are expired, click on the clock and trash icon. A warning message will pop up. To verify, click Delete All and the table will update by removing any door codes that have passed their expiration date.
<img width="493" alt="Screen Shot 2020-12-19 at 6 02 54 PM" src="https://user-images.githubusercontent.com/54377995/102703556-15173e00-4225-11eb-859a-83e46bc8f2b5.png">

2021-01-15 03:07 UTC, IsitaB reviewed
form validation: it doesn't add doorcodes at all if the formatting isn't right. maybe have an error message

consider letting the user input a number without dashes; render the doorcode with dashes tho

2021-02-02 02:24 UTC, aashrav requested changes
Remove comments an rebase

2021-02-02 02:24 UTC, aashrav commented on api/main_endpoints/routes/DoorCode.js
> +// router.post('/addCode', (req, res) => {
remove these comments

2021-02-02 02:24 UTC, aashrav commented on src/Pages/DoorCode/DoorCode.js
> +    // value = typeof value === 'undefined' ? '' : value;
remove comment

2021-02-02 02:24 UTC, aashrav commented on src/Pages/DoorCode/SVG.js
> +    // paste the <svg> and body from the website
remove comment

2021-02-02 02:24 UTC, aashrav commented on src/Pages/Overview/OverviewProfile.js
> +    // All the getDoor() logic in here
remove comment

2021-02-02 02:24 UTC, aashrav commented on src/Pages/Profile/admin/AdminView.jsx
> +    // All the getDoor() logic in here
remove

2021-02-02 02:24 UTC, aashrav commented on src/Pages/Profile/admin/AdminView.jsx
> +    // All the getDoor() logic in here
remove

2021-02-23 02:06 UTC, aashrav approved these changes
awesome!

2021-02-23 02:43 UTC, IsitaB requested changes
Please have the MemberView Profile page render the doorcode in the Profile doorcode block

Form validation por favor

2021-02-23 02:49 UTC, aashrav commented
> doorcode

In order to make this change make sure to edit MemberView/Profile.js...Currently they are trying to access the doorcode attribute from the User schema(which we took out). Instead you will need to call the getPersonsDoorCode() function and pass the email to get the doorcode. In addition, the form validation doesn't work...when I try to create a new doorcode without a date then it throws an error

2021-02-23 02:50 UTC, aashrav requested changes
In order to make this change make sure to edit MemberView/Profile.js...Currently they are trying to access the doorcode attribute from the User schema(which we took out). Instead you will need to call the getPersonsDoorCode() function and pass the email to get the doorcode. In addition, the form validation doesn't work...when I try to create a new doorcode without a date then it throws an error

2022-07-24 20:26 UTC, closed without merging