Sticky Navbar
SCE-Development/Core-v4 pull request #733
Opened 2020-12-24 19:19 UTC by fmasood23

2020-12-31 10:44 UTC, IsitaB requested changes
The navbar overlaps each page's first component. otw it works great :)

why do we need `margin-top:50px` in all these files? is there a better way to handle this?

2020-12-31 10:44 UTC, IsitaB commented on src/Components/Navbar/UserNavbar.js
> +    <div className={'user-nav'}>
get rid of the curly braces

2021-01-02 04:43 UTC, IsitaB requested changes
get rid of the hardcoded margin-tops

make the navbar's position:sticky instead

2021-01-02 04:43 UTC, IsitaB commented on src/Components/Navbar/UserNavbar.js
> +  useEffect(() =>
why do we need this? get rid of it

2021-01-02 05:04 UTC, IsitaB approved these changes

2021-01-03 09:25 UTC, jerrylee17 approved these changes

2021-01-04 03:29 UTC, IsitaB requested changes
delete the empty useEffect block and take package-lock out of the PR since you havent made any dependency changes

2021-01-05 05:44 UTC, IsitaB approved these changes

2021-01-08 03:38 UTC, merged