Refactored Events Page (Branch #2) -- Fixed text overlapping issue.
SCE-Development/Core-v4 pull request #738
Opened 2020-12-30 20:16 UTC by Annabel1054

2020-12-31 09:58 UTC, IsitaB requested changes

2020-12-31 09:58 UTC, IsitaB commented on .gitignore
>  *.cer
dont include this file in the PR

2020-12-31 09:58 UTC, IsitaB commented on src/Pages/EventManager/EventManager.js
> +        <div> <br></br> </div>
add padding to the button instead

2020-12-31 09:58 UTC, IsitaB commented on src/Pages/EventManager/EventManagerModal.js
> +              maxLength = {80}
okay. is the height of the card hardcoded bc this seems to be taking care of long descriptions?

2020-12-31 09:58 UTC, IsitaB commented on src/Pages/Events/EventCard.js
> +      <div className='event-text-block'>
text block position is hard coded not next to each other

2020-12-31 09:58 UTC, IsitaB commented on test/frontend/EventList.test.js
>        returnEventArray();
add in a test for your filtering functionality

2020-12-31 10:07 UTC, IsitaB requested changes
get rid of the onclick modal for Events.js

2020-12-31 10:16 UTC, IsitaB commented on test/frontend/EventList.test.js
> +    const result = wrapper.find('.no-event-list');
this isn't testing whether it would render 'no events yet'. you can add this code block to the previous test and it would pass

2021-01-01 01:17 UTC, ThaiQ requested changes
Dont commit package-lock.json, i will cause conflicts with others dev

2021-01-01 01:17 UTC, ThaiQ commented on src/Pages/Events/EventList.js
> +    <React.Fragment>
Do you need ReactFragment here?

2021-01-01 01:17 UTC, ThaiQ commented on src/Pages/EventManager/EventManager.js
> +    <React.Fragment>
Do you need React Fragment ?

2021-01-01 01:20 UTC, ThaiQ commented
ignore the React.Fragment comments

2021-01-02 01:55 UTC, IsitaB requested changes
the edit modal is dead for EventManager. I cant edit/delete events anymore

2021-01-03 07:39 UTC, IsitaB approved these changes
great work :)

2021-01-04 03:15 UTC, ThaiQ approved these changes

2021-01-04 03:38 UTC, aashrav requested changes
When you try to create an event it doesn't let you create it until the required fields are filled in. But if you type into a required field and then delete it, the create event button is still enabled. When you create the event it throws an error, but this could be designed better. Instead I believe that the button should always be enabled and if you try to create an event without required fields a message should show up on the modal saying "Required fields aren't filled in".

2021-01-06 07:54 UTC, IsitaB requested changes
yooo look at those form validation errors :')

functionality wise: you dont get the same form validation errors when youre trying to submit
<img width="1680" alt="Screen Shot 2021-01-05 at 11 46 25 PM" src="https://user-images.githubusercontent.com/50391828/103743178-b0900900-4fb0-11eb-92d1-246bb67eafd6.png">
in this screenshot, my title field is empty and it doesnt let me submit, but also doesnt tell me whats wrong

UI wise: the comment could look better; the dash dash isnt great
<img width="1680" alt="Screen Shot 2021-01-05 at 11 47 05 PM" src="https://user-images.githubusercontent.com/50391828/103743346-e2a16b00-4fb0-11eb-808d-c8f487bbe145.png">
`<fieldname> is required` or `please input <fieldname>`should suffice

2021-01-10 07:40 UTC, IsitaB reviewed
it works!!

but the modal code's repetitive 
this would be better https://serverless-stack.com/chapters/create-a-custom-react-hook-to-handle-form-fields.html

2021-01-11 04:49 UTC, law-nguyen approved these changes
it works for me

2021-01-11 05:00 UTC, fmasood23 approved these changes
it works for me as well!! looks good!

2021-01-11 05:01 UTC, aashrav approved these changes
Looks good. One thing I think should be fixed is that the events on the event manager should show up in chronological order like how they do on the actual events page.

2021-01-11 06:06 UTC, charlotte-zhuang reviewed
I was having issues with input validation for the time and date (I'm not sure if that's a separate issue). Overall, it looks alright to me.

On a side note, are the delete and cancel buttons are backwards in the ConfirmationModel component?

## Comments

1. Entering `12:00` as a time turns into 12:00 am. Also, `24:00` turns into 12:00 pm (but that's not a valid time anyway).
2. Invalid times are not rejected, e.g. `10:00 foo` or `hello`
3. Input validation errors in general are not mentioned (unless you leave a field blank).
4. Missing placeholder text for time and date.
5. I think using index for a component's key might cause issues (I think that's the default behavior if you don't specify a key)? I thought I ran into an error while deleting an event, but I couldn't reproduce it.
6. Creating or editing an event takes two clicks (this might be a problem with my setup)

2021-01-11 06:24 UTC, ThaiQ approved these changes

2021-01-11 17:18 UTC, merged