Create node.js.yml
SCE-Development/Core-v4 pull request #792
Opened 2021-02-23 01:11 UTC by Christopher-Tom

First try with Evan :)

2021-02-23 06:40 UTC, evanugarte commented
this is a work in progress, we arent done yet

2021-03-02 01:18 UTC, evanugarte requested changes

2021-03-02 01:18 UTC, evanugarte commented on .github/workflows/node.js.yml
> +    - run: npm ci
```suggestion
    - run: npm ci
    - run: cd ..
```

2021-03-08 17:25 UTC, evanugarte requested changes
Looks good! See comments

2021-03-08 17:25 UTC, evanugarte commented on .github/workflows/node.js.yml
> +# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
remove these comments, make the first line be what's on line 4 right now.

2021-03-08 17:25 UTC, evanugarte commented on .github/workflows/node.js.yml
> +name: Node.js CI
```suggestion
name: Core-v4 Tests
```

2021-03-08 17:25 UTC, evanugarte commented on .github/workflows/node.js.yml
> +    branches: [ dev ]
```suggestion
```

2021-03-08 17:25 UTC, evanugarte commented on .github/workflows/node.js.yml
> +    branches: [ dev ]
Lets remove this so the tests only run when a pr is open.

2021-03-08 17:25 UTC, evanugarte commented on .github/workflows/node.js.yml
> +
```suggestion
```

2021-03-08 17:25 UTC, evanugarte commented on .github/workflows/node.js.yml
> +
```suggestion
```

2021-03-08 17:25 UTC, evanugarte commented on .github/workflows/node.js.yml
> +
remove these lines

2021-03-09 00:53 UTC, evanugarte approved these changes
talk to em 🗣️

2021-03-09 01:05 UTC, hsorathia approved these changes

2021-03-09 01:07 UTC, seemavora approved these changes

2021-03-09 01:40 UTC, jerrylee17 approved these changes
I'd prefer keeping `.travis.yml` in case we can use travis again... Just make a note saying it does not work at the moment.

2021-03-09 02:43 UTC, IsitaB commented
Shouldn't we add `windows-latest` and `mac-latest` to the os list? Is ubuntu enough?

Which version of node does `matrix` pull? Can we change this to pull the node version from package.json?

2021-03-09 04:50 UTC, law-nguyen approved these changes
I too am curious about isita's comment, why only ubuntu?

2021-03-16 01:48 UTC, charlotte-zhuang requested changes
`matrix.node` is undefined.

2021-03-16 01:48 UTC, charlotte-zhuang commented on .github/workflows/node.js.yml
> +    - name: Use Node.js ${{ matrix.node }}
```suggestion
    - name: Use Node.js
```

2021-03-16 01:48 UTC, charlotte-zhuang commented on .github/workflows/node.js.yml
> +      with:
```suggestion
```

2021-03-16 01:48 UTC, charlotte-zhuang commented on .github/workflows/node.js.yml
> +        node-version: ${{ matrix.node }}
```suggestion
```

2021-03-18 03:33 UTC, charlotte-zhuang requested changes
`Run npm run frontend-tests` seems to have several connection refused errors. I couldn't find where they were being generated exactly. Can someone check on that? None of the tests are actually failing though.

Don't commit `package.json` and `package-lock.json`

2021-04-20 02:40 UTC, IsitaB requested changes
Please revert api/package-lock, package-lock

and ./package.json

Everything else works great!

2021-05-05 19:37 UTC, Christopher-Tom reviewed
yis, charlotte helped me with this

2021-05-08 19:15 UTC, Christopher-Tom reviewed
okay

2021-05-08 19:33 UTC, charlotte-zhuang approved these changes
`package.json` and `package-lock.json` changes are necessary or tests will fail. The last two commits aren't critical.

2021-05-08 20:33 UTC, merged