Google Login Page
SCE-Development/Core-v4 pull request #816
Opened 2021-03-21 21:57 UTC by Silenchezhian

Created as the frontend for SJSU SCE discord bot -- allows users to login and logout with gmail account. 
![image](https://user-images.githubusercontent.com/54826539/111922086-36bad800-8a55-11eb-83fa-7264b7802e2f.png)

If successful, user gets a message to type verify in discord channel and user information is printed in console.
![image](https://user-images.githubusercontent.com/54826539/111922162-91543400-8a55-11eb-81eb-d93311ea1fc4.png)

If failed, user gets an alert that the login failed. 
![image](https://user-images.githubusercontent.com/54826539/111922174-9ca75f80-8a55-11eb-83bc-13255ade69f0.png)

Need to generate and add REACT_APP_GOOGLE_CLIENT_ID to config.json in src.

2021-03-28 01:59 UTC, ThaiQ requested changes
Looking good!
1 changes: Please remove `package.json` and `package-lock.json` from commit. Follow this [link](https://devconnected.com/how-to-remove-files-from-git-commit/). You do ***NOT*** need to `git rm --cached <file>`.

2021-03-28 02:06 UTC, ThaiQ commented
also - for future references, name your branch as `firstname/topic` - ex: `sahana/googlelogin`

2021-03-30 01:43 UTC, ThaiQ approved these changes

2021-03-30 02:52 UTC, charlotte-zhuang reviewed
I guess we wouldn't want to merge this in to dev, since it's currently console logging the response from Google?

I'm also not sure where to get the react app google client id, so that might be causing some issues on my end.

1. I think we need to commit `package.json` at least, and preferably also a working `package-lock.json`
2. Nothing is logged to the console after I sign in with Google
3. There's no logout button

2021-04-06 00:40 UTC, ThaiQ commented
We are not merging yet - work in progress

2021-04-26 23:41 UTC, evanugarte commented on src/Pages/SJSUDiscordBot/GoogleLogin.js
> +  const getTempUser = () => {
can we put this in `APIFunctions`?

2021-04-26 23:42 UTC, evanugarte commented on src/Pages/SJSUDiscordBot/GoogleLogin.js
> +          </GoogleLogout>: <GoogleLogin
```suggestion
          <GoogleLogout
            clientId= {clientId}
            buttonText='Logout'
            onLogoutSuccess={ logout }
            onFailure={ onFailure }
          />: <GoogleLogin
```

2021-05-07 03:56 UTC, ThaiQ approved these changes
Clean!

2021-05-07 18:22 UTC, ThaiQ approved these changes

2021-05-08 18:16 UTC, charlotte-zhuang reviewed
This PR requires installing the `react-google-login` package.

I'm not sure how to test the functionality.

2021-05-08 18:16 UTC, charlotte-zhuang commented on src/Pages/SJSUDiscordBot/GoogleLogin.js
> +      if(!res.error){
```suggestion
      if (!res.error){
```
Minor complaint: it's better style to add a space between `if ()`

2021-05-08 18:16 UTC, charlotte-zhuang commented on src/Pages/SJSUDiscordBot/GoogleLogin.js
> +                <h5>Logout failed. Please try again or contact us. </h5>
```suggestion
                <h6>Logout failed. Please try again or contact us. </h6>
```
Nested headings should be a higher level.

2021-06-18 05:27 UTC, closed without merging