mongodb connection issue resolved
SCE-Development/Core-v4 pull request #918
Opened 2021-12-21 09:10 UTC by ajha7

MongoDB issue with using localhost for dbHost, replacing it with 127.0.0.1 seems to work.

2021-12-21 15:56 UTC, evanugarte commented
lint is failing, check build output for the fix

2021-12-21 17:02 UTC, allen-tran requested changes
as mentioned previously,linting

2021-12-22 03:45 UTC, evanugarte approved these changes

2021-12-22 03:56 UTC, allen-tran approved these changes
looks so good to me! wonderful job u are like a SRE

2021-12-22 04:00 UTC, merged