Rename logging_api directory to perpheral_api
SCE-Development/Core-v4 pull request #930
Opened 2021-12-24 07:48 UTC by allen-tran

Resolves #924

Renamed directory and all instances of `logging_api` or `LOGGING_API` to `peripheral_api`.

2021-12-24 18:31 UTC, ajha7 approved these changes

2021-12-24 19:53 UTC, evanugarte requested changes
- [ ] In the `config.example.jsons` update any instance of `loggingapi` to `peripheral_api`
- [ ] change the instantiation of the server in [api/peripheral_api/server.js:12](https://github.com/SCE-Development/Core-v4/blob/99062446765bae66f2b76dd3e0c6d4934da9f224/api/peripheral_api/server.js#L12)
to:
```js
  const peripheralServer = new SceHttpServer(API_ENDPOINTS, 8081, '/peripheral_api/');
  peripheralServer.initializeEndpoints().then(() => {
    peripheralServer.openConnection();
  });
```

2021-12-25 08:12 UTC, neelp03 approved these changes

2021-12-25 15:57 UTC, evanugarte requested changes

2021-12-25 15:57 UTC, evanugarte commented on package.json
> +    "start": "ESLINT_NO_DEV_ERRORS=true react-scripts start",
```suggestion
    "start": "react-scripts start",
```

2021-12-25 15:57 UTC, evanugarte commented on src/APIFunctions/2DPrinting.js
> +/* eslint-disable */
```suggestion
```

2021-12-25 15:57 UTC, evanugarte commented on src/APIFunctions/2DPrinting.js
> +  console.log({
noooooooooo

2021-12-25 15:57 UTC, evanugarte commented on api/peripheral_api/server.js
> +  SceHttpServer(API_ENDPOINTS, 8081, '/peripheral_api/');
if the prefix u are doing is `peripheral_api` make sure config.example.json matches, i believe is it is `peripheralapi` atm

2021-12-26 01:22 UTC, allen-tran commented
grrrrrrrrrr

2021-12-26 19:00 UTC, evanugarte approved these changes

2021-12-26 19:00 UTC, evanugarte commented on api/peripheral_api/models/PrintLog.js
> -      required: true
removing this for now because core-v4 has no way of knowing which printer was chosen atm

2021-12-26 19:04 UTC, merged