Created schema for reset token
SCE-Development/Core-v4 pull request #953
Opened 2022-01-10 23:15 UTC by crowbardispensingcore

2022-01-10 23:26 UTC, allen-tran requested changes

2022-01-10 23:26 UTC, allen-tran commented on api/main_endpoints/models/password-reset.js
> +    email: {
two things:
- [ ] the definition of the schema should follow the naming conventions of the other schemas
- [ ] the file name should also follow the naming convention of the other files in the models folder

2022-01-10 23:26 UTC, allen-tran commented on api/main_endpoints/models/password-reset.js
> +const mongoose = require('mongoose');
this only change should be this single file, you can undo the other changes by resetting it with dev with `git checkout origin/dev filename`

2022-01-10 23:26 UTC, allen-tran commented on api/main_endpoints/models/password-reset.js
> +);
this is solid tho and ily

2022-01-12 07:27 UTC, neelp03 requested changes

2022-01-12 07:27 UTC, neelp03 commented on package.json
> +    "server": "^1.0.37",
package.json should remain the same as dev right?

2022-01-18 19:43 UTC, closed without merging