Debug Frontend-test
SCE-Development/Core-v4 pull request #961
Opened 2022-01-12 02:50 UTC by andrewtedi

An error occurred as of late in which npm run frontend-test in Travis would hang until time exceeded or the workflow was terminated. This presents problems when it comes to our repository passing Travis checks. In order to prevent hanging, adding the "--exit" clause to the end of our frontend-test statement in package.json should do the trick. This will be proven if this PR passes the Travis check.

2022-01-12 02:52 UTC, evanugarte commented
lets see if the build finishes

2022-01-12 02:52 UTC, evanugarte commented
also we dont use travis

2022-01-12 02:53 UTC, andrewtedi commented
Oh right, we stopped using it a while back.

2022-01-19 19:35 UTC, evanugarte commented on .github/workflows/node.js.yml
> +    - run: node -v
```suggestion
```

2022-01-19 19:35 UTC, evanugarte commented on package.json
> +    "frontend-test": "mocha --require @babel/register --require ignore-styles test/frontend/*.js --exit",
```suggestion
    "frontend-test": "mocha --require @babel/register --require ignore-styles test/frontend/*.js",
```

2022-01-19 20:08 UTC, neelp03 requested changes
I think something went wrong in your changes, the build had been running for 30+ minutes

2022-01-19 20:48 UTC, allen-tran approved these changes
so sickness!!! 🔛 🔝 🔜 💯

2022-01-19 20:48 UTC, evanugarte commented on package.json
> +    "frontend-test": "mocha --require @babel/register --require ignore-styles test/frontend/*.js --exit",
hmm this didnt work. someone isnt calling `done` at the end of their tests...

2022-01-19 20:50 UTC, neelp03 approved these changes

2022-01-19 20:55 UTC, merged