Add DB schema for reset token
SCE-Development/Core-v4 pull request #962
Opened 2022-01-14 00:02 UTC by crowbardispensingcore

Add MongoDB schema for password reset token.
New collection: `passwordresets`
Fields:

- `email`
- `token`

2022-01-16 07:54 UTC, evanugarte requested changes

2022-01-16 07:54 UTC, evanugarte commented on api/main_endpoints/models/password-reset.js
> +const PasswordReset = new Schema(
```suggestion
const PasswordResetSchema = new Schema(
```

2022-01-26 05:42 UTC, evanugarte approved these changes

2022-01-26 05:59 UTC, neelp03 approved these changes
Looks good to me!

2022-01-27 06:15 UTC, merged