2D and 3D printing pages
SCE-Development/Core-v4 pull request #973
Opened 2022-01-27 04:57 UTC by Megan-J

updated the designs of the 2D and 3D printing pages

2022-02-11 05:17 UTC, evanugarte commented on src/Pages/3DPrinting/3DPrintForm.js
> +Team | © 2021 Software and Computer Engineering Society at SJSU`;
we dont have a copyright lol

to make this follow the current year no matter what, do

```suggestion
Team | Software and Computer Engineering Society at SJSU
 ${new Date().getFullYear()}`;
```

2022-02-11 05:17 UTC, evanugarte commented on src/Pages/3DPrinting/3D-print-form.css
> +@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300&family=Mina:wght@400;700&family=Ubuntu:wght@700&display=swap');
Is it possible we can use a different font that doesn't require a url? here are a bunch of css built-in fonts ([w3.org](https://www.w3.org/Style/Examples/007/fonts.en.html))

2022-02-18 21:54 UTC, andrewtedi reviewed
Looks good! Is it possible that instead of an input for Additional Comments that a textarea can be used instead? The box itself is too long and borders of the box reach over the container. Also, experiment with adding breaks after the copyright message, since there isn't enough extra space at the bottom.

2022-03-07 07:47 UTC, evanugarte approved these changes
Verified this locally, great work!!

2022-03-09 23:55 UTC, jessabelledelen requested changes
Hi Megan :) Good start and great job implementing the design! Just a couple things:

Was wondering why we're opting for drop-down lists for color & reason for usage instad of the original radio buttons design? 🥺 also wondering what this would mean for when a color is out of stock. Also, was wondering why we're doing a URL for .stl file versus a file upload.
They both work! Just wondering why we're swapping.

Category highlight is a little confusing -- it's okay that we're doing different tab designs from the Figma, but if the Current page we're on could be the tab with the lighter color to signify that it's selected, would be less confusing / more intuitive

Category tabs, and page contents like the text fields / dropdown lists shouldn't span entire width of the page / it'd be nice if we could focus them towards the center like the Figma design 

Footer should be at the absolute bottom of the page rather than the bottom of the page contents. With that, we could improve the vertical spacing of the elements and make it more uniform?

Again, wonderful start, Megan :) ❤️ Looking forward to future updates!!

Love, Jessabelle!!!

2022-03-10 20:14 UTC, Megan-J commented
@jessabelledelen 

Hi! Earlier in the semester, I showed my designs to Allen and Andrew and we agreed that the drop-downs would be easier to implement currently. If you still want to do the buttons, I can change the code. I chose to go with the URL for the .stl file versus a file upload since the backend currently isn't set up to support file uploads. 

I'll fix the other issues! :)

2022-03-31 20:19 UTC, jessabelledelen approved these changes
owowowo great job!!! ❤️ hard work pays off ily!!

2022-03-31 21:57 UTC, andrewtedi approved these changes

2022-03-31 21:57 UTC, andrewtedi commented on .eslintrc.json
> -    "parser": "@babel/eslint-parser",
pls add it back tyty

2022-03-31 22:11 UTC, merged