Better google script
SCE-Development/Core-v4 pull request #976
Opened 2022-01-28 04:10 UTC by crowbardispensingcore

Optimized adding google cloud credentials.

2022-01-28 04:41 UTC, neelp03 requested changes
The link that is given in the command line after providing the client id and client secret, does not update the client id parameter to the given client id

That link looks something like this: 

> `https://accounts.google.com/o/oauth2/v2/..../client_id=THIS_NEEDS_TO_CHANGE&redirect_uri=https%3A%2F%2Fdevelopers.google.com%2Foauthplayground`

Another thing I noticed was that the refresh token property in config.json does not get updated. 
> Note: After running the script, a token.js file is generated which has the refresh token.

2022-01-28 18:05 UTC, evanugarte commented on api/cloud_api/util/AuthManager.js
> +      }
![image](https://user-images.githubusercontent.com/36345325/151598781-7a1be70e-4eb2-45a2-9476-73b33dd26f20.png)

2022-02-19 02:26 UTC, neelp03 approved these changes

2022-02-19 05:04 UTC, andrewtedi approved these changes

2022-03-14 02:25 UTC, evanugarte approved these changes
Tested this locally with big paul and it works

2022-03-14 02:32 UTC, merged